version: '3.1'

services:
  db:
    container_name: sample_db
    image: postgres:9.5
    environment:
      - POSTGRES_PASSWORD=sample
      - POSTGRES_USER=sample
      - POSTGRES_DB=sample
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432